### ISSUE TITLE
CodeClimate's API-Key is needed

### ISSUE THREAD

**Issue by nobuyo** [13J-Programmers/4J-class-project#6]
## Outline

Refreshing CodeClimate from CircleCI needs API Token.
## Additinal Tasks
- [ ] Setup api key
- [ ] Fix command on circle.yml
#### Remarks

https://codeclimate.com/docs/api#repo-refresh

**Comment by tex2e** [comment]
Code Climate API tokens are currently only available for Code Climate organizations on **paid plans**. They are not currently available for users that only have open source repositories
