### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by tex2e** [13J-Programmers/4J-class-project#7]
## Outline

our node app (and game) needs to deploy to Heroku
## Changes
- [x] Deploy to Heroku
- [x] Automatically deploys from gh-pages
## Additinal Tasks
- [x] Link URL from README.md
### Remarks

[Continuous Deployment with Heroku](https://circleci.com/docs/continuous-deployment-with-heroku)

**Comment by tex2e** [comment]
deploy to https://n4js.herokuapp.com/

**Comment by TeX2e** [comment]
Close
